server:
  port: 9082

spring:
  application:
    name: customized
  datasource:
    url: jdbc:mysql://39.106.141.224:3306/customized?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: customized
    password: Customized123!@#
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
        minimum-idle: 5
        maximum-pool-size: 15
        auto-commit: true
        idle-timeout: 30000
        pool-name: DatebookHikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-init-sql: select 1

swagger:
  title: "${spring.application.name} API"
  description: "${spring.application.name} by swj"
  version: "0.0.1"
  basePackage: "com.swj.customized.controller"

mybatis:
    config-location: classpath:config/mybatis_config.xml
    mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:config/logback-spring.xml
  level:
    com.hcycom.acute.dto: debug


